-- Tell the club when somebody files a report, and tell the reporter it landed.
--
-- Fires supabase/functions/notify-feedback/index.ts. Design:
-- claude/plans/2026-08-18-help-and-feedback.md.
--
-- ══ ⚠️ IT MUST NEVER FAIL AN INSERT ══════════════════════════════════════
-- Three layers, exactly as private.notify_invite:
--   * net.http_post QUEUES and returns immediately;
--   * missing vault secrets WARN and return;
--   * the whole body is wrapped in `exception when others` -> warn -> return.
-- A dead mail path costs a prompt, not the report — and the report is the
-- thing that matters, because the SCREEN is the record and the e-mail is only
-- a nudge to go and look at it.
--
-- ══ ⚠️ INSERT ONLY ═══════════════════════════════════════════════════════
-- An UPDATE trigger would re-mail the club every time an admin moved a report
-- from `new` to `in-progress` — a notification generated by the act of reading
-- the last one, which is how a club learns to filter these to a folder.

begin;

create or replace function private.notify_feedback()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  endpoint text;
  secret   text;
begin
  -- ⚠️ READ FROM VAULT, NEVER HARDCODED. This file is committed to a PUBLIC
  -- repository.
  -- ⚠️ THE SHARED SECRET, NOT ONE OF ITS OWN. notify_approval, notify_invite,
  -- notify_pitch_request and the photo-backup cron all use
  -- `approval_notify_secret` with the header `x-approval-secret`. This file
  -- named a `feedback_notify_secret` first, which would have meant generating
  -- and hand-placing a credential to gain nothing.
  --
  -- ⚠️ THE URL IS DERIVED, NEVER TYPED — same as `photo_backup_url` in
  -- claude/runbooks/player-photo-backup.md. Deriving it from
  -- `approval_notify_url` means the project host cannot drift between secrets
  -- and nobody has to read, paste or retype a value.
  select decrypted_secret into endpoint
    from vault.decrypted_secrets where name = 'feedback_notify_url';
  select decrypted_secret into secret
    from vault.decrypted_secrets where name = 'approval_notify_secret';

  if endpoint is null or secret is null then
    raise warning 'notify_feedback: vault secrets missing, no email sent for feedback %', new.id;
    return new;
  end if;

  -- ⚠️ AN ID AND NOTHING ELSE. Every value in the mail — the reporter's own
  -- address most of all — is read back inside the function with the service
  -- role. A body carrying its own recipient would make this an open relay.
  perform net.http_post(
    url     := endpoint,
    headers := jsonb_build_object(
                 'Content-Type', 'application/json',
                 'x-approval-secret', secret),
    body    := jsonb_build_object('feedback_id', new.id)
  );

  return new;
exception when others then
  raise warning 'notify_feedback: % (feedback %)', sqlerrm, new.id;
  return new;
end;
$function$;

drop trigger if exists notify_feedback on public.feedback;
create trigger notify_feedback
  after insert on public.feedback
  for each row
  execute function private.notify_feedback();

-- ── THE GUARD ──────────────────────────────────────────────────────────
-- ⚠️ A migration that silently created nothing is the failure this catches.
do $$
declare n int;
begin
  select count(*) into n
    from pg_trigger t
    join pg_class c on c.oid = t.tgrelid
   where c.relname = 'feedback'
     and t.tgname = 'notify_feedback'
     and not t.tgisinternal;
  if n <> 1 then
    raise exception 'notify_feedback trigger not installed (found %)', n;
  end if;
end $$;

commit;
