// Builds the installed-app icon set from src/assets/crest.png.
//
// Run by hand, from the repo root:
//   node harness/make-icons.mjs
//
// ⚠️ IT WRITES STRAIGHT INTO public/icons/. Check `git diff --stat` after, and
// look at the PNGs, before committing — this is a design asset, and the only
// real test of it is somebody's eyes at 48px on a phone.
//
// ⚠️ WHY THIS EXISTS AT ALL. The previous icon set (PR #99) was generated by
// hand and left no script, so the artwork could not be regenerated, re-measured
// or adjusted without redoing the whole job from scratch. That is what made
// Jay's "remove all the wording" a research task rather than a parameter
// change. Icons are derived artefacts; deriving them should be repeatable.
//
// Playwright is NOT a dependency of this repo (see harness/playwright.mjs for
// the reasoning) — it is resolved at runtime, exactly like the shoot scripts.
// Install for a one-off run with:
//   npm i -D playwright --no-save && npx playwright install chromium
//
// ── What it does, and the traps each step exists to avoid ──────────────────
//
// Jay's brief, 14 Aug 2026, in the order it arrived:
//   1. keep the crest, not the bat mark
//   2. "remove all the wording from the logo"
//   3. "put Club Hub inside the logo white part, above the bat"
//   4. "can we make the logo look somewhat 3d"
//   5. white tile background
//
// (2) then (3) is not a contradiction: stripping the club's name and founding
// year clears the field, and CLUB HUB is two short words that survive being
// small far better than the four lines the crest carries.

import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { loadChromium } from './playwright.mjs'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const REPO = path.join(HERE, '..')
const OUT = path.join(REPO, 'public/icons')
mkdirSync(OUT, { recursive: true })

const crestB64 = readFileSync(path.join(REPO, 'src/assets/crest.png')).toString('base64')
// Inter 900 — the app's own display weight (tailwind.config.js fontFamily.display),
// read from public/fonts/ rather than trusting whatever the OS happens to have.
const fontB64 = readFileSync(path.join(REPO, 'public/fonts/inter-900.woff2')).toString('base64')

const chromium = await loadChromium()
const browser = await chromium.launch()
const page = await browser.newPage()

const prep = await page.evaluate(async ({ b64, fontB64 }) => {
  const face = new FontFace('InterIcon', `url(data:font/woff2;base64,${fontB64}) format('woff2')`, { weight: '900' })
  await face.load()
  document.fonts.add(face)

  const img = new Image()
  img.src = 'data:image/png;base64,' + b64
  await img.decode()
  const W = img.naturalWidth, H = img.naturalHeight

  const src = document.createElement('canvas')
  src.width = W; src.height = H
  const sctx = src.getContext('2d')
  sctx.drawImage(img, 0, 0)
  const im = sctx.getImageData(0, 0, W, H)
  const d = im.data
  const at = (x, y) => (y * W + x) * 4

  const isRed = (i) => d[i + 3] > 40 && d[i] > 110 && d[i + 1] < 95 && d[i + 2] < 95
  const isGreen = (i) => d[i + 3] > 40 && d[i + 1] > 100 && d[i] < 160 && d[i + 2] < 140
  const isClear = (i) => d[i + 3] <= 40

  // ── flood from the edge through {transparent, red} ──────────────────────
  // Swallows the shield's red BORDER, so the red LETTERING is left behind as
  // unreached islands. Without this the border and the wordmark are the same
  // colour and cannot be told apart.
  const outer = new Uint8Array(W * H)
  {
    const st = []
    for (let x = 0; x < W; x++) st.push(x, 0, x, H - 1)
    for (let y = 0; y < H; y++) st.push(0, y, W - 1, y)
    while (st.length) {
      const y = st.pop(), x = st.pop()
      if (x < 0 || y < 0 || x >= W || y >= H) continue
      const k = y * W + x
      if (outer[k]) continue
      const i = k * 4
      if (!(isClear(i) || isRed(i))) continue
      outer[k] = 1
      st.push(x + 1, y, x - 1, y, x, y + 1, x, y - 1)
    }
  }

  // The border red, sampled before anything is overwritten. CLUB HUB is set in
  // it so the mark keeps exactly two inks.
  let rr = 0, rg = 0, rb = 0, rn = 0
  for (let y = 150; y < 250; y++) for (let x = 0; x < 12; x++) {
    const i = at(x, y); if (isRed(i)) { rr += d[i]; rg += d[i + 1]; rb += d[i + 2]; rn++ }
  }
  const RED = rn ? `rgb(${Math.round(rr / rn)},${Math.round(rg / rn)},${Math.round(rb / rn)})` : '#c8102e'

  // ── 1. the wordmark ─────────────────────────────────────────────────────
  // ⚠️ EVERY interior pixel above the bat goes flat white, NOT just the ones
  // that test as red. Keying on colour leaves the letters' ANTI-ALIASED
  // FRINGES, and the wordmark stays perfectly legible as pale pink outlines.
  // Bounded at y < 88: the bat's first black pixels are at y≈90 and the
  // wordmark's lowest at y=79.
  let wiped = 0
  for (let y = 0; y < 88; y++) for (let x = 0; x < W; x++) {
    const k = y * W + x, i = k * 4
    if (outer[k] || isClear(i)) continue
    d[i] = 255; d[i + 1] = 255; d[i + 2] = 255; d[i + 3] = 255
    wiped++
  }

  // ── 2. RUGBY CLUB / 1970 on the green panel ────────────────────────────
  let gr = 0, gg = 0, gb = 0, gn = 0
  for (let y = 300; y < 340; y++) for (let x = 150; x < 220; x++) {
    const i = at(x, y); if (isGreen(i)) { gr += d[i]; gg += d[i + 1]; gb += d[i + 2]; gn++ }
  }
  const G = gn ? [Math.round(gr / gn), Math.round(gg / gn), Math.round(gb / gn)] : [122, 192, 81]

  // ⚠️ KEYED ON DISTANCE FROM THE PANEL GREEN, and bracketed per row by the
  // panel's own extent. Two earlier attempts failed identically: white-on-green
  // anti-aliasing runs through PALE GREENS that satisfy isGreen() perfectly
  // well, so glyph cores were replaced while their fringes were classified as
  // panel — leaving an embossed, readable ghost of "RUGBY CLUB".
  //
  // Threshold 12, not 30: at 30 a letter-shaped residue of 7–18px per row
  // survived on the "1970" line. Measured by the residual pass below, not
  // guessed at.
  const glyph = []
  for (let y = 250; y < H; y++) {
    let lo = -1, hi = -1
    for (let x = 0; x < W; x++) if (isGreen(at(x, y))) { if (lo < 0) lo = x; hi = x }
    if (lo < 0) continue
    for (let x = lo; x <= hi; x++) {
      const i = at(x, y)
      if (isClear(i) || isRed(i)) continue
      if (Math.hypot(d[i] - G[0], d[i + 1] - G[1], d[i + 2] - G[2]) > 12) glyph.push(i)
    }
  }
  for (const i of glyph) { d[i] = G[0]; d[i + 1] = G[1]; d[i + 2] = G[2]; d[i + 3] = 255 }

  // Residual: anything still deviating inside the panel is a ghost that got
  // away. Reported so a future tweak cannot quietly reintroduce one.
  let residual = 0
  for (let y = 250; y < H; y++) {
    let lo = -1, hi = -1
    for (let x = 0; x < W; x++) if (isGreen(at(x, y))) { if (lo < 0) lo = x; hi = x }
    if (lo < 0) continue
    for (let x = lo; x <= hi; x++) {
      const i = at(x, y)
      if (isClear(i) || isRed(i)) continue
      if (Math.hypot(d[i] - G[0], d[i + 1] - G[1], d[i + 2] - G[2]) > 12) residual++
    }
  }

  sctx.putImageData(im, 0, 0)

  // ── 3. CLUB HUB in the cleared field ───────────────────────────────────
  // Width is measured from the shield at the text's own baseline rather than
  // assumed: the shield tapers, so a fixed box would overflow at the shoulders
  // or float undersized lower down.
  const textY = 52
  let lo = W, hi = 0
  for (let x = 0; x < W; x++) {
    const k = textY * W + x
    if (!outer[k] && !isClear(k * 4)) { if (x < lo) lo = x; if (x > hi) hi = x }
  }
  const avail = (hi - lo) * 0.82
  sctx.textAlign = 'center'
  sctx.textBaseline = 'middle'
  sctx.fillStyle = RED
  sctx.font = `900 60px InterIcon`
  const label = 'CLUB HUB'
  const size = Math.floor(60 * (avail / sctx.measureText(label).width))
  sctx.font = `900 ${size}px InterIcon`
  sctx.fillText(label, (lo + hi) / 2, textY)

  // ── 4. a light 3D treatment ────────────────────────────────────────────
  // ⚠️ ALL OF IT source-atop, so every stop is clipped to the shield's own
  // alpha. Painted normally it squares the crest off inside a grey box.
  //
  // ⚠️ The top white is 0.10. At 0.20 the shield's red border went visibly pink
  // across the shoulders and the mark read as faded — the wash cost more in
  // brand red than the volume was worth. Bevels and hard speculars were never
  // considered: they read as 2005 web chrome and disintegrate at 48px.
  sctx.globalCompositeOperation = 'source-atop'
  const vol = sctx.createLinearGradient(0, 0, 0, H)
  vol.addColorStop(0, 'rgba(255,255,255,0.10)')
  vol.addColorStop(0.42, 'rgba(255,255,255,0.01)')
  vol.addColorStop(0.72, 'rgba(0,0,0,0.12)')
  vol.addColorStop(1, 'rgba(0,0,0,0.34)')
  sctx.fillStyle = vol
  sctx.fillRect(0, 0, W, H)

  const gloss = sctx.createRadialGradient(W * 0.34, H * 0.10, 4, W * 0.34, H * 0.10, W * 0.72)
  gloss.addColorStop(0, 'rgba(255,255,255,0.18)')
  gloss.addColorStop(0.55, 'rgba(255,255,255,0.03)')
  gloss.addColorStop(1, 'rgba(255,255,255,0)')
  sctx.fillStyle = gloss
  sctx.fillRect(0, 0, W, H)
  sctx.globalCompositeOperation = 'source-over'

  // ── 5. true extent, from the ALPHA mask ────────────────────────────────
  // The shield tapers, so its bounding box overstates it. The furthest opaque
  // pixel from the centroid is the honest radius, and using it lets the crest
  // sit meaningfully larger inside the safe circle.
  const fin = sctx.getImageData(0, 0, W, H).data
  let sx = 0, sy = 0, n = 0
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) if (fin[at(x, y) + 3] > 40) { sx += x; sy += y; n++ }
  const cx = sx / n, cy = sy / n
  let maxR = 0
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    if (fin[at(x, y) + 3] > 40) { const r = Math.hypot(x - cx, y - cy); if (r > maxR) maxR = r }
  }

  window.__clean = { url: src.toDataURL('image/png'), cx, cy, maxR }
  return { wiped, glyphs: glyph.length, residual, green: G, red: RED, textPx: size, cx, cy, maxR }
}, { b64: crestB64, fontB64 })

if (prep.residual > 0) {
  console.error(`\n⚠️  ${prep.residual} px of lettering residue left on the green panel — a ghost got away.\n`)
}

async function compose({ size, maskable, bg, name }) {
  const { dataUrl, outside } = await page.evaluate(async ({ size, maskable, bg }) => {
    const { url, cx, cy, maxR } = window.__clean
    const img = new Image(); img.src = url; await img.decode()
    const c = document.createElement('canvas')
    c.width = size; c.height = size
    const ctx = c.getContext('2d')
    if (bg) { ctx.fillStyle = bg; ctx.fillRect(0, 0, size, size) }

    // ⚠️ THE SHADOW COUNTS TOWARD THE SAFE ZONE. Blur and offset extend past
    // the artwork, so the target radius is reduced by exactly that much —
    // otherwise "0% outside the safe circle" is true of the crest and false of
    // the icon that ships.
    const blur = size * 0.035, offY = size * 0.018
    const target = (maskable ? size * 0.4 : size * 0.48) - (blur + offY)
    const scale = target / maxR

    ctx.save()
    ctx.shadowColor = 'rgba(0,0,0,0.38)'
    ctx.shadowBlur = blur
    ctx.shadowOffsetY = offY
    ctx.translate(size / 2, size / 2 - offY * 0.3)
    ctx.scale(scale, scale)
    ctx.drawImage(img, -cx, -cy)
    ctx.restore()

    // Measure mask-safety on the RENDERED tile rather than trusting the maths:
    // share of non-background pixels falling outside the 80% safe circle.
    let out = 0, ink = 0
    const px = ctx.getImageData(0, 0, size, size).data
    const R = size * 0.4, mid = size / 2
    // On a filled tile every pixel is opaque, so "ink" means "differs from the
    // background colour" — that is what a mask would actually clip away.
    const bgPix = bg ? ctx.getImageData(1, 1, 1, 1).data : null
    for (let y = 0; y < size; y++) for (let x = 0; x < size; x++) {
      const i = (y * size + x) * 4
      const isInk = bgPix
        ? Math.hypot(px[i] - bgPix[0], px[i + 1] - bgPix[1], px[i + 2] - bgPix[2]) > 10
        : px[i + 3] > 20
      if (!isInk) continue
      ink++
      if (Math.hypot(x - mid, y - mid) > R) out++
    }
    return { dataUrl: c.toDataURL('image/png'), outside: ink ? +(100 * out / ink).toFixed(2) : 0 }
  }, { size, maskable, bg })
  writeFileSync(path.join(OUT, name), Buffer.from(dataUrl.split(',')[1], 'base64'))
  return { name, outside }
}

const WHITE = '#ffffff'
const written = []
// `any` — transparent, used where the platform does not mask.
written.push(await compose({ size: 512, maskable: false, bg: null, name: 'icon-512.png' }))
written.push(await compose({ size: 192, maskable: false, bg: null, name: 'icon-192.png' }))
// `maskable` — Jay chose the white tile, 14 Aug 2026.
written.push(await compose({ size: 512, maskable: true, bg: WHITE, name: 'maskable-512.png' }))
written.push(await compose({ size: 192, maskable: true, bg: WHITE, name: 'maskable-192.png' }))
// iOS applies its own squircle and does not honour transparency well.
written.push(await compose({ size: 180, maskable: false, bg: WHITE, name: 'apple-touch-icon.png' }))
written.push(await compose({ size: 32, maskable: false, bg: null, name: 'favicon-32.png' }))

console.log(JSON.stringify({ ...prep, written }, null, 2))

const bad = written.filter((w) => w.name.startsWith('maskable') && w.outside > 0)
if (bad.length) {
  console.error(`\n⚠️  MASKABLE ICONS ARE NOT MASK-SAFE: ${bad.map((b) => `${b.name} ${b.outside}%`).join(', ')}\n`)
  process.exitCode = 1
}

await browser.close()
