-- ══════════════════════════════════════════════════════════════════════════
--  GRANTS — table-level, column-level and default privileges in `public`
--  Captured from Supabase project lusmshimxdcxpnrktlgz (Postgres 17)
--  on 2026-08-10.
--
--  ⚠️ READ, DO NOT RUN. Like the rest of `db/schema/`, this is a snapshot
--  written to be diffed. It is not a migration.
-- ══════════════════════════════════════════════════════════════════════════
--
-- WHY THIS FILE EXISTS
--
-- `db/schema/README.md` carried this warning from 9 Aug 2026:
--
--     ⚠️ `db/schema/` DOES NOT CAPTURE GRANTS ON TABLES OR COLUMNS. The larger
--     half of `20260808191310 profile_phone_and_column_grants` is a
--     column-level REVOKE/GRANT on `profiles` — the thing standing between a
--     member and rewriting someone's login email — and nothing in this
--     directory would diff it.
--
-- It was right, and `claude/state-of-play.md` called it "the one real gap …
-- and nothing currently checks it". This file is that gap closed. A clean
-- reconciliation of the other four files still says nothing about grants; a
-- clean reconciliation *including this one* does.
--
-- ⚠️ POSTGRES KEEPS NO TIMESTAMP FOR A GRANT. That is why this had to become a
-- captured file rather than a periodic audit: once an unintended grant exists,
-- nothing in the catalogue can say when it appeared or who made it. The 9 Aug
-- capture already hit this with five `proacl` lines in `functions.sql` that
-- could not be attributed to any migration. A diff against a committed
-- snapshot is the only mechanism that answers "did this change".
--
-- HOW TO RE-CAPTURE. Three queries, in the Supabase SQL editor. Re-run them
-- with the migration, not three days later — the diff is only useful while it
-- is small enough to read.
--
--   -- 1. table-level
--   select c.relname,
--          case when a.grantee = 0 then 'PUBLIC' else a.grantee::regrole::text end,
--          string_agg(a.privilege_type, ', ' order by a.privilege_type)
--   from pg_class c
--   join pg_namespace n on n.oid = c.relnamespace
--   cross join lateral aclexplode(c.relacl) a
--   where n.nspname = 'public' and c.relkind in ('r','v','m','p','f')
--   group by 1,2 order by 1,2;
--
--   -- 2. column-level
--   select c.relname, att.attname,
--          case when a.grantee = 0 then 'PUBLIC' else a.grantee::regrole::text end,
--          string_agg(a.privilege_type, ', ' order by a.privilege_type)
--   from pg_class c
--   join pg_namespace n on n.oid = c.relnamespace
--   join pg_attribute att on att.attrelid = c.oid and att.attnum > 0
--                        and not att.attisdropped
--   cross join lateral aclexplode(att.attacl) a
--   where n.nspname = 'public'
--   group by 1,2,3 order by 1,2,3;
--
--   -- 3. default privileges (what a NEW object will be born with)
--   select coalesce(n.nspname,'(all)'), d.defaclrole::regrole::text, d.defaclobjtype,
--          case when a.grantee = 0 then 'PUBLIC' else a.grantee::regrole::text end,
--          string_agg(a.privilege_type, ', ' order by a.privilege_type)
--   from pg_default_acl d
--   left join pg_namespace n on n.oid = d.defaclnamespace
--   cross join lateral aclexplode(d.defaclacl) a
--   group by 1,2,3,4 order by 1,2,3,4;
--
-- ⚠️ FUNCTION `EXECUTE` GRANTS ARE **NOT** HERE. They are captured as `proacl`
-- lines in `functions.sql` and have been since 7 Aug. Do not duplicate them —
-- a second copy of a fact is a copy that drifts.


-- ── 1. DEFAULT PRIVILEGES ──────────────────────────────────────────────────
--
-- ⚠️ THE MOST IMPORTANT BLOCK IN THIS FILE, AND THE LEAST OBVIOUS. Supabase
-- ships `public` with default privileges that hand `anon` and `authenticated`
-- FULL table rights on every table created there, from BOTH `postgres` and
-- `supabase_admin` as granting role:
--
--     DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
--
-- So a new table in `public` is born reachable by an anonymous visitor, and
-- **RLS is the only thing between it and the internet.** Creating a table and
-- forgetting `enable row level security` is not a hardening oversight, it is a
-- public table. Every table in `public` does currently have RLS enabled —
-- `tables.sql` records that, and it is worth re-reading it as a load-bearing
-- fact rather than a tidy one.
--
-- This is stock Supabase and is NOT something to "fix" here: the whole PostgREST
-- model depends on those grants existing and RLS doing the filtering. It is
-- written down because the consequence is invisible from the DDL.
--
--   schema  granting role     object      grantee         privileges
--   public  postgres          tables      anon            ALL 8
--   public  postgres          tables      authenticated   ALL 8
--   public  postgres          tables      postgres        ALL 8
--   public  postgres          tables      service_role    ALL 8
--   public  supabase_admin    tables      anon            ALL 8
--   public  supabase_admin    tables      authenticated   ALL 8
--   public  supabase_admin    tables      postgres        ALL 8
--   public  supabase_admin    tables      service_role    ALL 8
--   public  (both)            sequences   anon/auth/pg/sr SELECT, UPDATE, USAGE
--   public  (both)            functions   anon/auth/pg/sr EXECUTE
--
-- ⚠️ `functions … EXECUTE` to `anon` is why every new `SECURITY DEFINER`
-- function is anon-callable the moment it is created. `state-of-play.md`
-- records that the anon-executable ones all fail safe, by three different
-- routes. That is a property of each function body, not of the grants — and
-- this default is why it has to be checked for every new one.


-- ── 2. TABLE-LEVEL GRANTS ──────────────────────────────────────────────────
--
-- Almost every table in `public` grants all eight privileges to all four of
-- `anon`, `authenticated`, `postgres` and `service_role` — which is exactly what
-- the default privileges above produce — with the exceptions listed below, and
-- the exceptions are the whole point of the file.
--
-- ⚠️ THE COUNT THAT USED TO OPEN THIS PARAGRAPH SAID "FOURTEEN" AND WAS WRONG BY
-- 12 Aug 2026, when league_teams and the three match-sheet tables landed. Removed
-- rather than corrected: it is a number in a capture, and this repo has watched
-- every one of those rot. The list below is the record; count it if you need one.
--
-- ⚠️ `attendance` (10 Aug) IS SECTION 1 PROVING ITSELF. Its migration writes no
-- GRANT at all, and it arrived with all eight privileges for `anon` anyway. The
-- only thing between that table and anyone holding the project URL is the
-- `enable row level security` line in the same migration.
--
--   access_requests   anon, authenticated, postgres, service_role   ALL 8
--   attendance        anon, authenticated, postgres, service_role   ALL 8
--   availability      anon, authenticated, postgres, service_role   ALL 8
--   calendar_tokens   anon, authenticated, postgres, service_role   ALL 8
--   clubs             anon, authenticated, postgres, service_role   ALL 8
--   events            anon, authenticated, postgres, service_role   ALL 8
--   invite_targets    anon, authenticated, postgres, service_role   ALL 8
--   invites           anon, authenticated, postgres, service_role   ALL 8
--   memberships       anon, postgres, service_role                  ALL 8
--   memberships       authenticated    ← NO table-level UPDATE, as of 10 Aug
--                                        2026. DELETE, INSERT, MAINTAIN,
--                                        REFERENCES, SELECT, TRIGGER, TRUNCATE
--   league_teams      anon, authenticated, postgres, service_role   ALL 8
--                     ⚠️ ADDED 12 Aug 2026, and the `anon` row is Supabase's
--                     DEFAULT PRIVILEGES rather than intent — the migration
--                     grants nothing. RLS is the only thing keeping anon out,
--                     and it does: `league team read` requires a non-null
--                     auth.uid(), verified live by db/tests/rls-league-teams.sql
--                     (anon reads zero rows). This is the same shape the note
--                     at the top of this file describes for every new table.
--   match_sheets      anon, authenticated, postgres, service_role   ALL 8
--   match_sheet_slots anon, authenticated, postgres, service_role   ALL 8
--   match_sheet_cards anon, authenticated, postgres, service_role   ALL 8
--                     ⚠️ ADDED 12 Aug 2026. As with league_teams, the `anon`
--                     row is Supabase's DEFAULT PRIVILEGES and not intent —
--                     the migration grants nothing on these tables. RLS is
--                     what keeps anon out: all three policies resolve through
--                     private.can_edit_team, which tests auth.uid() against
--                     memberships and cannot match a null uid.
--   photo_backup_runs postgres, service_role                        ALL 8
--   photo_backup_runs authenticated    ← SELECT ONLY
--   photo_backup_runs anon             ← NOTHING AT ALL
--                     ⚠️ ADDED 13 Aug 2026, and it is THE FIRST TABLE IN THIS
--                     SCHEMA WHERE `anon` HOLDS NO PRIVILEGE. Every note above
--                     says the `anon` row is Supabase's default rather than
--                     intent, and leans on RLS to keep anon out. Here the
--                     default was revoked as well, so RLS is not standing alone.
--                     ⚠️ IF A RE-CAPTURE EVER SHOWS anon BACK ON THIS TABLE,
--                     that is drift, not a version difference — the revoke is in
--                     db/migrations/20260813_photo_backup.sql.
--                     ⚠️ AND service_role STILL HAS ALL 8 INCLUDING DELETE. The
--                     migration asks for SELECT, INSERT, UPDATE and comments
--                     "no DELETE: a run row is a record of what happened" —
--                     ⚠️ THAT COMMENT DESCRIBES THE GRANT, NOT THE OUTCOME.
--                     Supabase's default privileges had already given
--                     service_role everything, and a GRANT cannot take a
--                     privilege away. Measured after applying, not assumed.
--   photo_orphan_scans postgres, service_role                       ALL 8
--   photo_orphan_scans authenticated   ← NOTHING AT ALL
--   photo_orphan_scans anon            ← NOTHING AT ALL
--                     ⚠️ ADDED 16 Aug 2026, and the SECOND table where `anon`
--                     holds nothing — but the FIRST where `authenticated` holds
--                     nothing either. Measured after applying: the table came
--                     out of `create table` with the full set granted to
--                     `authenticated` by Supabase's DEFAULT PRIVILEGES, and it
--                     was revoked in the same migration.
--                     ⚠️ RLS ALREADY DENIED EVERYTHING (the table has NO
--                     policies), so that grant was inert — and that is exactly
--                     why it was worth taking back rather than shrugging at.
--                     The day somebody adds a policy for an admin screen the
--                     ceiling would already be wide open, and the policy would
--                     be the only thing deciding. Grants are the ceiling, RLS
--                     is the gate.
--                     ⚠️ A RE-CAPTURE SHOWING EITHER ROLE BACK IS DRIFT, not a
--                     version difference — the revokes are in
--                     db/migrations/20260816_photo_orphan_scan.sql.
--   pitch_requests    anon, authenticated, postgres, service_role   ALL 8
--   pitches           anon, authenticated, postgres, service_role   ALL 8
--   player_contacts   anon, authenticated, postgres, service_role   ALL 8
--   player_parents    anon, authenticated, postgres, service_role   ALL 8
--   players           anon, authenticated, postgres, service_role   ALL 8
--   teams             anon, authenticated, postgres, service_role   ALL 8
--
--   profiles          anon, postgres, service_role                  ALL 8
--   profiles          authenticated    ← NO UPDATE. DELETE, INSERT, MAINTAIN,
--                                        REFERENCES, SELECT, TRIGGER, TRUNCATE
--
-- "ALL 8" throughout means:
--   DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE
-- (`MAINTAIN` is new in Postgres 17. A capture taken against an older server
-- will show seven and that is a version difference, not drift.)
--
-- ⚠️ THE ASYMMETRY IS DELIBERATE BUT ONE-SIDED, AND WAS NOT WRITTEN DOWN
-- ANYWHERE UNTIL NOW. `20260808_profile_phone_and_column_grants.sql` revoked
-- table-level UPDATE on `profiles` from `authenticated` and granted it back on
-- five named columns. It did NOT revoke it from `anon`, which still holds
-- table-level UPDATE on `profiles`.
--
-- Measured, not assumed: `anon` is stopped by RLS alone. Both UPDATE policies
-- on `profiles` are role `PUBLIC` — so they do apply to `anon` — and both fail
-- for a null uid:
--     profile update own          USING (id = auth.uid())
--     profile update club admin   USING private.shares_admin_club(id)
-- `id = null` is null, not true, and an anonymous caller shares no admin club.
-- So there is no live hole. But the defence-in-depth that `authenticated` has
-- is absent for `anon`, and the belt is doing the work the braces were added
-- for. Recorded rather than changed: revoking it is a one-line migration with
-- a real chance of breaking a signup path nobody has re-tested.


-- ── 3. COLUMN-LEVEL GRANTS ─────────────────────────────────────────────────
--
-- The only column-level grants in the entire `public` schema. They exist
-- because table-level UPDATE was taken away above.
--
-- ⚠️ THE SENTENCE ABOVE SAID "Five columns of one table" UNTIL 13 Aug 2026, by
-- which point it named neither the right number nor the right number of tables
-- — `memberships` joined on 10 Aug. A count in a heading is a thing that rots;
-- the list below is the inventory.
--
--   profiles.first_name         authenticated   UPDATE
--   profiles.full_name          authenticated   UPDATE
--   profiles.last_name          authenticated   UPDATE
--   profiles.name_confirmed_at  authenticated   UPDATE
--   profiles.phone              authenticated   UPDATE
--   profiles.no_player_confirmed_at  authenticated  SELECT, UPDATE  ← 16 Aug 2026
--
--   memberships.profile_id      authenticated   UPDATE
--   memberships.club_id         authenticated   UPDATE
--   memberships.team_id         authenticated   UPDATE
--   memberships.player_id       authenticated   UPDATE
--   memberships.role            authenticated   UPDATE
--   memberships.status          authenticated   UPDATE
--   memberships.title           authenticated   UPDATE   ← 13 Aug 2026
--
-- ⚠️ `profiles.no_player_confirmed_at` IS THE SECOND TIME THIS TRAP WAS MET AND
-- THE FIRST TIME IT WAS SEEN COMING. Added 16 Aug 2026 for the sign-in gate,
-- with its grant in the same migration — because `memberships.title` below had
-- already shown what happens without one. It also needs SELECT, unlike the five
-- above it: those are covered by the table-level SELECT `authenticated` still
-- holds, and so is this one — the explicit grant is belt-and-braces against a
-- future revoke, and costs nothing.
--
-- ⚠️ `memberships.title` IS WHY THIS SECTION IS NOT BOOKKEEPING. It is the first
-- column added to `memberships` since the table-level UPDATE was revoked, and
-- without its own grant (20260813_membership_title.sql) the save fails with
-- something that reads exactly like an RLS refusal on a policy that is working
-- correctly. **The fix for that failure is a COLUMN grant. Never
-- `grant update on public.memberships to authenticated`** — that would restore
-- write access to `is_super` and make the super-admin tier theatre again, with
-- no test failing and nothing visible in the app.
--
-- ⚠️ `memberships` JOINED THIS LIST ON 10 Aug 2026, and for exactly the reason
-- `profiles.email` is on it. `is_super` and `admin_rights` are NOT granted.
--
-- `memb manage` is FOR ALL and admin-only, so ANY ADMIN CAN ALREADY WRITE
-- MEMBERSHIP ROWS — including their own. Without the revoke, any admin could
-- set `is_super = true` on themselves and the super-admin tier would be
-- theatre. **RLS cannot close that**: the policy authorises the ROW, and "an
-- admin may write membership rows in their club" is true both before and after
-- the row gains the flag. Only a column privilege limits WHICH FIELDS.
--
-- The one write path is `public.set_admin_rights`, SECURITY DEFINER, which
-- checks `private.is_super_admin()` first and raises rather than returning
-- quietly — a silent no-op would look exactly like success on screen.
-- Harness: `db/tests/rls-super-admin.sql`, which proves an ordinary admin is
-- refused on the UPDATE path, the RPC path AND the INSERT path, that an
-- ordinary admin can still write the columns it should, and that a real super
-- admin can do all of it. That last part matters: a build that refuses
-- EVERYONE looks identical from the ordinary admin's side alone.
--
-- ⚠️ INSERT IS NOT COLUMN-RESTRICTED, deliberately — a column grant on INSERT
-- would block the DEFAULTS too, so an ordinary `insert into memberships (...)`
-- would fail. The insert path is guarded by the RESTRICTIVE policy
-- `memb no self promotion` instead, which refuses a new row that arrives
-- already carrying the flag or any rights.
--
-- ⚠️ WHAT IS NOT ON THAT LIST IS THE POINT. `profiles` has eight columns; the
-- three excluded are:
--
--   id          — the auth user id. The join to `auth.users` and to every
--                 membership row.
--   created_at  — audit.
--   email       — ⚠️ THE ONE THAT MATTERS. This is the login identity. Without
--                 the revoke, `profile update own` (USING id = auth.uid())
--                 would let any signed-in member rewrite their own row's email
--                 — and `profile update club admin` would let a club admin
--                 rewrite ANY member's. The RLS policy authorises the ROW; only
--                 the column grant limits WHICH FIELDS. Nothing else in the
--                 database stops it.
--
-- ⚠️ SO THE POLICY LIST AND THE POLICY BODIES CANNOT TELL YOU THIS. Reading
-- `policies.sql` alone, `profile update own` looks like "a member may edit
-- their own profile", full stop. The five-column ceiling on that sentence lives
-- only here and in the migration. That gap is why this file had to exist.
--
-- Adding a column to `profiles` therefore has a decision attached: a new column
-- is NOT updatable by a member until it is granted, and it SHOULD only be
-- granted if a member editing it is intended. The failure mode is silent in
-- both directions — an ungranted column makes a save fail with a permission
-- error that looks like RLS, and an over-granted one hands out a field nobody
-- meant to expose.
--
-- Checked by `db/tests/grants.sql`, which asserts this list exactly and fails
-- loudly on either kind of drift.


-- ── 4. ⚠️ THE ONE-CLICK WAY TO DESTROY ALL OF THIS ─────────────────────────
--
-- Found in the Supabase dashboard on 10 Aug 2026, and it is the most dangerous
-- thing in this file.
--
-- **Integrations → Data API → Settings → Exposed tables** lists the tables in
-- `public`. All but one carry a green tick. `public.profiles` does not: it
-- is rendered in AMBER with a warning icon, and its tooltip reads
--
--     "This table has custom grants. Select it to override with standard Data
--      API grants for anon, authenticated, and service_role."
--
-- ⚠️ THE "PROBLEM" IT OFFERS TO FIX IS THE PROTECTION ITSELF. `profiles` is
-- flagged precisely BECAUSE table-level UPDATE was revoked from `authenticated`
-- and re-granted on five named columns — the thing standing between a club admin
-- and rewriting any member's login email. Clicking that row to make the amber
-- warning go away would "override with standard grants", hand table-level UPDATE
-- straight back, and silently undo section 3 of this file.
--
-- ⚠️ AND IT WOULD LOOK LIKE TIDYING UP. The dashboard presents it as an
-- inconsistency; the row is the only one not matching its neighbours; the fix is
-- one click, with no confirmation describing what is lost. Nothing in the app
-- would change, no test would fail, and no error would appear anywhere — this app
-- never attempts that write, so the extra privilege stays invisible until
-- somebody uses it.
--
-- **DO NOT CLICK IT. The amber row is correct, and must stay amber.**
--
-- What would catch it: `db/tests/grants.sql` fails immediately (`authenticated`
-- can UPDATE profiles.email), and a re-capture would diff section 2 back to a
-- uniform thirteen. ⚠️ **Both are manual.** Nothing automatic can see a dashboard.


-- ---------------------------------------------------------------------
-- public.social_ideas — COLUMN grants  (captured 12 Aug 2026)
--
-- ⚠️ POLICIES AUTHORISE THE ROW; GRANTS AUTHORISE THE COLUMN. "social idea
-- decide" is FOR UPDATE over the whole row, so without this an admin marking
-- an idea used is also authorised to rewrite the submitter's words and swap
-- their photo. Same protection as profiles.email, and §4 above records how
-- readily the Supabase dashboard offers to undo exactly this.
--
-- Verified after applying: table-level UPDATE to `authenticated` is NONE, and
-- the column list is exactly these four.
-- ---------------------------------------------------------------------
REVOKE UPDATE ON public.social_ideas FROM authenticated;
GRANT UPDATE (status, decision_note, decided_by, decided_at)
  ON public.social_ideas TO authenticated;


-- ---------------------------------------------------------------------
-- public.announcements — TABLE and COLUMN grants  (captured 14 Aug 2026)
--
-- Captured from information_schema.column_privileges and
-- .table_privileges after applying 20260814_announcements.sql — NOT pasted
-- from the migration.
--
-- ⚠️ `team_id` IS THE ONE THAT MATTERS, AND IT IS ABSENT FROM THE UPDATE LIST
-- ON PURPOSE. A notice's audience is fixed when it is posted. "announcement
-- edit" is FOR UPDATE over the whole row, so without this revoke an author
-- could re-scope a squad notice to the WHOLE CLUB after thirty families had
-- already read it — and the read receipts would then be counted against an
-- audience that never saw it, with nothing on the row to show it had happened.
-- The policy does not stop this; only the missing grant does.
--
-- ⚠️ `author_id`, `club_id` and `created_at` are absent for the same class of
-- reason: they are stamped by `announcements_provenance` and an admin editing a
-- typo must not be able to reassign authorship.
--
-- ⚠️ `updated_at` IS ALSO ABSENT, AND IT IS NOT AN OVERSIGHT. It is written by
-- the `announcements_touch` trigger, so an edit cannot claim not to have
-- happened — which is the only thing that column is for.
--
-- VERIFIED IN THE CAPTURE: table-level UPDATE to `authenticated` is NONE, and
-- the column-level UPDATE list for `authenticated` is exactly these four.
-- ---------------------------------------------------------------------
GRANT SELECT, INSERT, DELETE ON public.announcements TO authenticated;
REVOKE UPDATE ON public.announcements FROM authenticated;
GRANT UPDATE (title, body, pinned, expires_at)
  ON public.announcements TO authenticated;


-- ---------------------------------------------------------------------
-- public.announcement_reads — TABLE grants  (captured 14 Aug 2026)
--
-- ⚠️ NO UPDATE, AND NO UPDATE OR DELETE POLICY EITHER, so a read cannot be
-- un-read or back-dated. `read_at` therefore means FIRST read, which is what
-- the word means. The client upserts with `ignoreDuplicates`.
--
-- ⚠️ THE CAPTURE SHOWS `authenticated` HOLDING TABLE-LEVEL **DELETE** HERE,
-- WHICH THIS MIGRATION NEVER GRANTED. It comes from Supabase's own
-- `alter default privileges in schema public grant all on tables to anon,
-- authenticated, service_role`. It is inert — RLS is enabled and there is no
-- DELETE policy, so no row is deletable — but it is inert BY THE POLICY rather
-- than by the grant. Recorded as found; see the note below.
-- ---------------------------------------------------------------------
GRANT SELECT, INSERT ON public.announcement_reads TO authenticated;
REVOKE UPDATE ON public.announcement_reads FROM authenticated;


-- ---------------------------------------------------------------------
-- ⚠️ `anon` HOLDS FULL TABLE PRIVILEGES ON EVERY TABLE IN `public`, INCLUDING
-- THESE TWO. MEASURED 14 Aug 2026, NOT REASONED ABOUT.
--
--   announcements, announcement_reads, social_ideas, events, players,
--   memberships, match_sheets
--     -> anon: DELETE,INSERT,REFERENCES,SELECT,TRIGGER,TRUNCATE,UPDATE
--
-- Every one of the seven probed came back identical, so this is the schema's
-- pre-existing shape and NOT something the notices migration introduced. The
-- source is the same Supabase default-privileges line quoted above.
--
-- ⚠️ IT IS THE TABLE-LEVEL SIBLING OF THE FUNCTION-LEVEL FINDING RECORDED IN
-- `db/migrations/20260813_my_squad_staff.sql`, where six RPCs turned out to be
-- callable by `anon` for exactly this reason. The conclusion is the same one
-- that migration reached: these are safe today by their POLICIES, which all
-- test `auth.uid()` (null for `anon`), rather than by their grants — and this
-- repo's own rule says not to rely on that.
--
-- ⚠️ DELIBERATELY NOT FIXED HERE. Tightening only the two newest tables would
-- leave the schema inconsistent while fixing nothing an attacker could reach;
-- it is one migration across all of `public` or it is not worth doing. Logged
-- in `claude/state-of-play.md` §Open.
-- ---------------------------------------------------------------------


-- ---------------------------------------------------------------------
-- public.announcement_stats() / public.announcement_audience(uuid)
--   (captured 14 Aug 2026)
--
-- ⚠️ THE EXPLICIT `FROM anon` IS LOAD-BEARING, not belt-and-braces — see the
-- header of db/migrations/20260813_my_squad_staff.sql. `REVOKE … FROM PUBLIC`
-- does NOT remove Supabase's by-name grant to `anon`.
--
-- Both are SECURITY DEFINER, so RLS is bypassed inside them and their own
-- WHERE clause (`author_id = auth.uid() OR private.is_admin(club_id)`) is the
-- only gate on the club's entire notice history.
-- ---------------------------------------------------------------------
REVOKE EXECUTE ON FUNCTION public.announcement_stats() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.announcement_stats() FROM anon;
GRANT EXECUTE ON FUNCTION public.announcement_stats() TO authenticated;

REVOKE EXECUTE ON FUNCTION public.announcement_audience(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.announcement_audience(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.announcement_audience(uuid) TO authenticated;


-- ---------------------------------------------------------------------
-- public.lineups / public.lineup_players — TABLE grants  (captured 14 Aug 2026)
--
-- Captured from information_schema.table_privileges after applying
-- 20260814_match_lineups.sql — NOT pasted from the migration, which is the whole
-- point of this file. The two disagree, and the disagreement is the useful part.
--
-- ⚠️ THE MIGRATION GRANTED `SELECT, INSERT, UPDATE, DELETE`. THE CAPTURE SHOWS
-- `authenticated` ALSO HOLDING `TRUNCATE`, `REFERENCES` AND `TRIGGER`, which it
-- never granted. Same cause as the note on `announcement_reads` above: Supabase's
-- own `alter default privileges in schema public grant all on tables to anon,
-- authenticated, service_role`. Recorded as FOUND.
--
-- ⚠️ `TRUNCATE` IS THE ONE WORTH KNOWING ABOUT, BECAUSE TRUNCATE BYPASSES RLS.
-- It is inert through the API — PostgREST exposes SELECT/INSERT/UPDATE/DELETE and
-- has no TRUNCATE route — so nothing a client can send reaches it. It is NOT new
-- and NOT specific to these tables: the same default has applied to every table
-- in `public`. Left alone deliberately rather than revoked on two tables while
-- twenty-four others keep it, which would make the schema less consistent, not
-- more. **If it is ever tidied, tidy it schema-wide in its own migration.**
--
-- ✅ `anon` DOES NOT APPEAR FOR EITHER TABLE, AND THAT IS THE LOAD-BEARING LINE.
-- The 14 Aug grants sweep revoked anon across `public`, but it revoked EXISTING
-- tables — it did not change the DEFAULT PRIVILEGES that decide what a NEW one
-- gets, and `pg_default_acl` still holds a supabase_admin entry that includes
-- anon. The migration's explicit `revoke all ... from anon` is why anon is absent
-- here. Fault-injected against live the same day: `set local role anon; select
-- from lineups` raises 42501 — refused by the GRANT, not merely returned empty.
-- ---------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lineups        TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lineup_players TO authenticated;
REVOKE ALL ON public.lineups        FROM anon;
REVOKE ALL ON public.lineup_players FROM anon;


-- ---------------------------------------------------------------------
-- public.player_grades / public.player_positions — TABLE grants
-- (captured 14 Aug 2026 from information_schema.table_privileges)
--
-- ⚠️ TWO TABLES, DELIBERATELY DIFFERENT VISIBILITY, AND THE GRANTS LOOK
-- IDENTICAL BECAUSE THE DIFFERENCE IS IN THE POLICIES, NOT HERE. Both give
-- `authenticated` the four verbs; what separates them is that
-- `player grade manage` is can_edit_team on BOTH read and write with NO wider
-- read arm — so a PARENT CANNOT READ THEIR OWN CHILD'S GRADE — while
-- `player position read` is deliberately squad-wide. Anyone reading only this
-- file would conclude the two are the same; they are not.
--
-- ⚠️ `authenticated` ALSO HOLDS TRUNCATE / REFERENCES / TRIGGER, which neither
-- migration granted. Supabase's own `alter default privileges ... grant all on
-- tables` again — same note as lineups above, same conclusion: inert through
-- PostgREST, not new, and if it is ever tidied it should be tidied schema-wide.
--
-- ✅ `anon` APPEARS FOR NEITHER TABLE. That is the explicit revoke in each
-- migration, and for player_grades it is the line that matters most in this
-- file: it holds a judgement about a child's ability. Fault-injected the same
-- day — anon gets 42501, and an authenticated caller with no membership reads
-- zero rows and is refused 42501 on a write.
-- ---------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE, DELETE ON public.player_grades    TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.player_positions TO authenticated;
REVOKE ALL ON public.player_grades    FROM anon;
REVOKE ALL ON public.player_positions FROM anon;
